install:
	sudo pip install flask
	sudo pip install pandas
	sudo pip install nltk
	sudo pip install sklearn

install3:
	sudo pip3 install flask
	sudo pip3 install pandas
	sudo pip3 install nltk
	sudo pip3 install sklearn

run: 
	python irModel.py

run3:
	python3 irModel.py
